
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrlyfiqgreoxedzfjqwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybHlmaXFncmVveGVkemZqcXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDUwMTEsImV4cCI6MjA2MjkyMTAxMX0.rtZC36QMaKpHQL7wuu3WPx2WCZZ6nylboUyUS9T7qSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Helper function to check if connected
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('cards').select('count').limit(1);
    if (error) {
      console.error("Supabase connection error:", error);
      return false;
    }
    console.log("Supabase connection successful");
    return true;
  } catch (e) {
    console.error("Supabase connection check failed:", e);
    return false;
  }
};
